name: intake-gui
channels:
  - conda-forge
dependencies:
  - intake
  - jupyter
  - nodejs
  - scipy
  - scikit-image
  - s3fs
  - tqdm
  - intake-xarray
  - bokeh/label/dev::bokeh
  - pyviz/label/dev::hvplot
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::panel
